package org.servlet.webapp.servlet.models.entities;

import jakarta.persistence.*;

// Marks the class as a JPA entity to be mapped to a database table
@Entity
@Table(name = "categorias") // Specifies the table name in the database
public class Categoria {

    // Indicates the primary key field
    @Id
    // Auto-generates the ID using the identity strategy in the database
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // The ID of the category, will be generated by the database
    private Long id;

    // The name of the category
    private String nombre;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}
